services:
  pc2mqtt:
    image: nana4rider/pc2mqtt:latest
    container_name: pc2mqtt
    volumes:
      - ~/config/pc2mqtt/config.json:/app/config.json:ro
      - ~/config/pc2mqtt/.ssh:/home/node/.ssh
    env_file:
      - ~/config/common/base.env
      - ~/config/common/mqtt.env
      - ~/config/pc2mqtt/app.env
    network_mode: host
    restart: always
