services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    networks:
      - common_network
    command: tunnel --no-autoupdate run --token ${TOKEN}
    restart: always
    labels:
      - "diun.enable=true"

networks:
  common_network:
    external: true
