services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:2025.10.0
    container_name: cloudflared-tunnel
    networks:
      - common_network
    command: tunnel --no-autoupdate run --token ${TOKEN}
    restart: always

networks:
  common_network:
    external: true
