services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/data/diun:/data
    env_file:
      - ~/config/common/base.env
      - ~/config/diun/app.env
    command: serve
    restart: always
    labels:
      - "diun.enable=true"
