name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  dclint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v6

      - name: Run dclint
        run: npx dclint **/compose.yaml
